//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApBusiness.Domains
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class V3Entities : DbContext
    {
        public V3Entities()
            : base("name=V3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Change_Code> Change_Code { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Function> Functions { get; set; }
        public DbSet<LookUp> LookUps { get; set; }
        public DbSet<PaymentTerm> PaymentTerms { get; set; }
        public DbSet<Product_Price> Product_Price { get; set; }
        public DbSet<Project_Client> Project_Client { get; set; }
        public DbSet<SIV> SIVs { get; set; }
        public DbSet<SRV> SRVs { get; set; }
        public DbSet<Stock_File> Stock_File { get; set; }
        public DbSet<Stock_Picture> Stock_Picture { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<Store_Stock> Store_Stock { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<WAMS_ASSIGNING_WORKER> WAMS_ASSIGNING_WORKER { get; set; }
        public DbSet<WAMS_ASSIGNING_WORKER_TOOLS> WAMS_ASSIGNING_WORKER_TOOLS { get; set; }
        public DbSet<WAMS_ASSIGNNING_STOCKS> WAMS_ASSIGNNING_STOCKS { get; set; }
        public DbSet<WAMS_ATTACHMENT> WAMS_ATTACHMENT { get; set; }
        public DbSet<WAMS_AUDIT> WAMS_AUDIT { get; set; }
        public DbSet<WAMS_AUDIT_TRAILS> WAMS_AUDIT_TRAILS { get; set; }
        public DbSet<WAMS_BRAND_FUEL> WAMS_BRAND_FUEL { get; set; }
        public DbSet<WAMS_CAR> WAMS_CAR { get; set; }
        public DbSet<WAMS_CAR_FUELOIL_DETAIL> WAMS_CAR_FUELOIL_DETAIL { get; set; }
        public DbSet<WAMS_CATALOGUE_CONFIGURATION> WAMS_CATALOGUE_CONFIGURATION { get; set; }
        public DbSet<WAMS_CATEGORY> WAMS_CATEGORY { get; set; }
        public DbSet<WAMS_COMPANY_DETAILS> WAMS_COMPANY_DETAILS { get; set; }
        public DbSet<WAMS_CONSUMABLE_LIST> WAMS_CONSUMABLE_LIST { get; set; }
        public DbSet<WAMS_COUNTRY> WAMS_COUNTRY { get; set; }
        public DbSet<WAMS_CURRENCY_TYPE> WAMS_CURRENCY_TYPE { get; set; }
        public DbSet<WAMS_CURRENT_SUPERVISOR> WAMS_CURRENT_SUPERVISOR { get; set; }
        public DbSet<WAMS_DESCRIPTION> WAMS_DESCRIPTION { get; set; }
        public DbSet<WAMS_EQUIPMENT> WAMS_EQUIPMENT { get; set; }
        public DbSet<WAMS_EQUIPMENT_FUELOIL_DETAIL> WAMS_EQUIPMENT_FUELOIL_DETAIL { get; set; }
        public DbSet<WAMS_ERROR_MESSAGE> WAMS_ERROR_MESSAGE { get; set; }
        public DbSet<WAMS_FUEL_OIL> WAMS_FUEL_OIL { get; set; }
        public DbSet<WAMS_FULFILLMENT_DETAIL> WAMS_FULFILLMENT_DETAIL { get; set; }
        public DbSet<WAMS_FUNCTION_MANAGEMENT> WAMS_FUNCTION_MANAGEMENT { get; set; }
        public DbSet<WAMS_HISTORY_ACTION> WAMS_HISTORY_ACTION { get; set; }
        public DbSet<WAMS_HISTORY_FORM> WAMS_HISTORY_FORM { get; set; }
        public DbSet<WAMS_HISTORY_LOG> WAMS_HISTORY_LOG { get; set; }
        public DbSet<WAMS_HISTORY_OBJECT> WAMS_HISTORY_OBJECT { get; set; }
        public DbSet<WAMS_IMAGES> WAMS_IMAGES { get; set; }
        public DbSet<WAMS_ITEMS_SERVICE> WAMS_ITEMS_SERVICE { get; set; }
        public DbSet<WAMS_LABELS> WAMS_LABELS { get; set; }
        public DbSet<WAMS_MEASUREMENT> WAMS_MEASUREMENT { get; set; }
        public DbSet<WAMS_PAINT> WAMS_PAINT { get; set; }
        public DbSet<WAMS_PO_DETAILS> WAMS_PO_DETAILS { get; set; }
        public DbSet<WAMS_PO_EVALUATION> WAMS_PO_EVALUATION { get; set; }
        public DbSet<WAMS_PO_Info> WAMS_PO_Info { get; set; }
        public DbSet<WAMS_PO_TYPE> WAMS_PO_TYPE { get; set; }
        public DbSet<WAMS_POSITION> WAMS_POSITION { get; set; }
        public DbSet<WAMS_PRODUCT> WAMS_PRODUCT { get; set; }
        public DbSet<WAMS_PROJECT> WAMS_PROJECT { get; set; }
        public DbSet<WAMS_PROJECT_SUPERVISOR> WAMS_PROJECT_SUPERVISOR { get; set; }
        public DbSet<WAMS_PURCHASE_ORDER> WAMS_PURCHASE_ORDER { get; set; }
        public DbSet<WAMS_REPORT> WAMS_REPORT { get; set; }
        public DbSet<WAMS_REPORT_DETAILS> WAMS_REPORT_DETAILS { get; set; }
        public DbSet<WAMS_REQUISITION_DETAILS> WAMS_REQUISITION_DETAILS { get; set; }
        public DbSet<WAMS_REQUISITION_MASTER> WAMS_REQUISITION_MASTER { get; set; }
        public DbSet<WAMS_RETURN_LIST> WAMS_RETURN_LIST { get; set; }
        public DbSet<WAMS_RETURN_PRODUCT_TO_SUPPLIER> WAMS_RETURN_PRODUCT_TO_SUPPLIER { get; set; }
        public DbSet<WAMS_RETURNING_WORKER_TOOLS> WAMS_RETURNING_WORKER_TOOLS { get; set; }
        public DbSet<WAMS_SCAFOLDING> WAMS_SCAFOLDING { get; set; }
        public DbSet<WAMS_SERVICE> WAMS_SERVICE { get; set; }
        public DbSet<WAMS_SERVICE_ALERT_CONFIG> WAMS_SERVICE_ALERT_CONFIG { get; set; }
        public DbSet<WAMS_SERVICE_HISTORY> WAMS_SERVICE_HISTORY { get; set; }
        public DbSet<WAMS_SHIPMENT> WAMS_SHIPMENT { get; set; }
        public DbSet<WAMS_SHIPMENT_DETAIL> WAMS_SHIPMENT_DETAIL { get; set; }
        public DbSet<WAMS_SPAREPART> WAMS_SPAREPART { get; set; }
        public DbSet<WAMS_STOCK> WAMS_STOCK { get; set; }
        public DbSet<WAMS_STOCK_ALERT_CONFIG> WAMS_STOCK_ALERT_CONFIG { get; set; }
        public DbSet<WAMS_STOCK_APPROVAL> WAMS_STOCK_APPROVAL { get; set; }
        public DbSet<WAMS_STOCK_LOG> WAMS_STOCK_LOG { get; set; }
        public DbSet<WAMS_STOCK_LOW> WAMS_STOCK_LOW { get; set; }
        public DbSet<WAMS_STOCK_MANAGEMENT_QUANTITY> WAMS_STOCK_MANAGEMENT_QUANTITY { get; set; }
        public DbSet<WAMS_STOCK_STATUS> WAMS_STOCK_STATUS { get; set; }
        public DbSet<WAMS_STOCK_TYPE> WAMS_STOCK_TYPE { get; set; }
        public DbSet<WAMS_STOCKIN> WAMS_STOCKIN { get; set; }
        public DbSet<WAMS_SUB_CATEGORY> WAMS_SUB_CATEGORY { get; set; }
        public DbSet<WAMS_SUPERVISOR> WAMS_SUPERVISOR { get; set; }
        public DbSet<WAMS_SUPPLIER> WAMS_SUPPLIER { get; set; }
        public DbSet<WAMS_SUPPLIER_SERVICE> WAMS_SUPPLIER_SERVICE { get; set; }
        public DbSet<WAMS_SUPPLIER_TYPE> WAMS_SUPPLIER_TYPE { get; set; }
        public DbSet<WAMS_TYPE_FUEL> WAMS_TYPE_FUEL { get; set; }
        public DbSet<WAMS_UNIT> WAMS_UNIT { get; set; }
        public DbSet<WAMS_USEFOR> WAMS_USEFOR { get; set; }
        public DbSet<WAMS_USER> WAMS_USER { get; set; }
        public DbSet<WAMS_USERALERT> WAMS_USERALERT { get; set; }
        public DbSet<WAMS_WAREHOUSE> WAMS_WAREHOUSE { get; set; }
        public DbSet<WAMS_WARRANTY_EXPIRE_ALERT> WAMS_WARRANTY_EXPIRE_ALERT { get; set; }
        public DbSet<WAMS_WORKER> WAMS_WORKER { get; set; }
        public DbSet<WAMS_WORKER_STATUS> WAMS_WORKER_STATUS { get; set; }
    }
}
