//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIV
    {
        public int Id { get; set; }
        public string SIV1 { get; set; }
        public string vStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
