//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_Stock
    {
        public int Id { get; set; }
        public int Store { get; set; }
        public int StockID { get; set; }
        public decimal Quantity { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
