//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.WAMS_USER = new HashSet<WAMS_USER>();
        }
    
        public int Id { get; set; }
        public string sName { get; set; }
        public string sCode { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Phone { get; set; }
        public string Description { get; set; }
        public Nullable<bool> iEnable { get; set; }
        public Nullable<System.DateTime> dCreated { get; set; }
        public Nullable<System.DateTime> dModified { get; set; }
        public Nullable<int> iCreated { get; set; }
        public Nullable<int> iModified { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual ICollection<WAMS_USER> WAMS_USER { get; set; }
    }
}
