//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_STOCK_LOG
    {
        public long bStockLogID { get; set; }
        public string vUserName { get; set; }
        public Nullable<System.DateTime> dActionDate { get; set; }
        public string vActionName { get; set; }
        public string FormName { get; set; }
        public string vStockID { get; set; }
        public string vStockName { get; set; }
        public string vStockType { get; set; }
        public Nullable<System.DateTime> dDate { get; set; }
        public Nullable<double> bQuantity { get; set; }
        public string vProjectName { get; set; }
        public string StockCondition { get; set; }
        public string vDescription { get; set; }
    }
}
