//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_ATTACHMENT
    {
        public long iAttachmentID { get; set; }
        public byte[] bAttachment { get; set; }
        public string vAttachmentName { get; set; }
        public System.DateTime dDate { get; set; }
    }
}
