//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_COMPANY_DETAILS
    {
        public long iCompanyID { get; set; }
        public string vCompanyName { get; set; }
        public string vCompanyDetail { get; set; }
        public string vCompanyPhone { get; set; }
        public string vFax { get; set; }
        public string vAddress { get; set; }
        public string vEmail { get; set; }
        public string vSite { get; set; }
        public string vCity { get; set; }
        public string vCountry { get; set; }
        public string TaxCode { get; set; }
        public string ContactPerson { get; set; }
    }
}
