//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_CAR
    {
        public WAMS_CAR()
        {
            this.WAMS_CAR_FUELOIL_DETAIL = new HashSet<WAMS_CAR_FUELOIL_DETAIL>();
        }
    
        public long bCarID { get; set; }
        public string vCarID { get; set; }
        public string vPlateNo { get; set; }
        public Nullable<int> iRegistrationFrequency { get; set; }
        public Nullable<System.DateTime> dLastRegistration { get; set; }
        public Nullable<long> bPositionID { get; set; }
        public string vColor { get; set; }
        public string vDescription { get; set; }
        public string vModel { get; set; }
        public string vCondition { get; set; }
    
        public virtual ICollection<WAMS_CAR_FUELOIL_DETAIL> WAMS_CAR_FUELOIL_DETAIL { get; set; }
        public virtual WAMS_POSITION WAMS_POSITION { get; set; }
    }
}
