//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_PO_DETAILS
    {
        [Key]
        public int ID { get; set; }
        public Nullable<int> vPOID { get; set; }
        public string vUnit { get; set; }
        public string vInvoiceNo { get; set; }
        public Nullable<System.DateTime> dInvoiceDate { get; set; }
        public Nullable<int> vMRF { get; set; }
        public Nullable<int> iDiscount { get; set; }
        public Nullable<int> vProductID { get; set; }
        public Nullable<decimal> fQuantity { get; set; }
        public Nullable<int> fVAT { get; set; }
        public Nullable<decimal> fImportTax { get; set; }
        public Nullable<decimal> fUnitPrice { get; set; }
        public Nullable<decimal> fItemTotal { get; set; }
        public Nullable<System.DateTime> dDeliveryDate { get; set; }
        public Nullable<bool> iEnable { get; set; }
        public string vRemark { get; set; }
        public string vPODetailStatus { get; set; }
        public Nullable<System.DateTime> dDateAssign { get; set; }
        public Nullable<int> PriceId { get; set; }
        public Nullable<System.DateTime> dCreated { get; set; }
        public Nullable<System.DateTime> dModified { get; set; }
        public Nullable<int> iCreated { get; set; }
        public Nullable<int> iModified { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
