//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_ITEMS_SERVICE
    {
        [Key]
        public int Id { get; set; }
        public string vIDServiceItem { get; set; }
        public string vServiceItemName { get; set; }
        public string vDescription { get; set; }
        public Nullable<int> bCategoryID { get; set; }
        public Nullable<int> bUnitID { get; set; }
        public Nullable<int> bPositionID { get; set; }
        public Nullable<long> bSupplierID { get; set; }
        public string vStockType { get; set; }
        public Nullable<bool> iEnable { get; set; }
        public Nullable<double> bWeight { get; set; }
        public string vAccountCode { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<System.DateTime> dCreated { get; set; }
        public Nullable<System.DateTime> dModified { get; set; }
        public Nullable<int> iCreated { get; set; }
        public Nullable<int> iModified { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
