//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_PO_TYPE
    {
        public WAMS_PO_TYPE()
        {
            this.WAMS_PURCHASE_ORDER = new HashSet<WAMS_PURCHASE_ORDER>();
        }
    
        public int bPOTypeID { get; set; }
        public string vPOTypeName { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual ICollection<WAMS_PURCHASE_ORDER> WAMS_PURCHASE_ORDER { get; set; }
    }
}
