//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_WARRANTY_EXPIRE_ALERT
    {
        [Key]
        public long bWarrantyExpire { get; set; }
        public Nullable<long> bWarrantyDate { get; set; }
        public Nullable<int> bTimesNumberShow { get; set; }
        public string vStockID { get; set; }
    }
}
