//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_RETURNING_WORKER_TOOLS
    {
        public long bWorkerReturnID { get; set; }
        public string vWorkerID { get; set; }
        public string vStockID { get; set; }
        public double bQuantity { get; set; }
        public System.DateTime dDateReturn { get; set; }
        public string vStatus { get; set; }
        public Nullable<double> IssuedQuantity { get; set; }
    
        public virtual WAMS_WORKER WAMS_WORKER { get; set; }
    }
}
