//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_PO_Info
    {
        public string NameUser { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string CC { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
