//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_LABELS
    {
        public long bLabelID { get; set; }
        public string vLabelName { get; set; }
        public string isDislay1 { get; set; }
        public string isDislay2 { get; set; }
        public string isDislay3 { get; set; }
        public string isDislay4 { get; set; }
        public string isDislay5 { get; set; }
        public string isDislay6 { get; set; }
        public string vColorsmall { get; set; }
        public string vColorbig { get; set; }
        public int iTypeLabel { get; set; }
        public string vStockType { get; set; }
        public Nullable<int> iType { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
