//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_WORKER
    {
        public WAMS_WORKER()
        {
            this.WAMS_ASSIGNING_WORKER = new HashSet<WAMS_ASSIGNING_WORKER>();
            this.WAMS_ASSIGNING_WORKER_TOOLS = new HashSet<WAMS_ASSIGNING_WORKER_TOOLS>();
            this.WAMS_PROJECT = new HashSet<WAMS_PROJECT>();
            this.WAMS_RETURNING_WORKER_TOOLS = new HashSet<WAMS_RETURNING_WORKER_TOOLS>();
        }

        [Key]
        public string vWorkerID { get; set; }
        public string vFirstName { get; set; }
        public string vLastName { get; set; }
        public Nullable<System.DateTime> dDateOfBirth { get; set; }
        public string vAddress { get; set; }
        public string vPhone { get; set; }
        public string vMobile { get; set; }
        public Nullable<long> bPositionID { get; set; }
        public string vDetail { get; set; }
        public string vRemark { get; set; }
        public string vPhotoPath { get; set; }
        public int iEnable { get; set; }
    
        public virtual ICollection<WAMS_ASSIGNING_WORKER> WAMS_ASSIGNING_WORKER { get; set; }
        public virtual ICollection<WAMS_ASSIGNING_WORKER_TOOLS> WAMS_ASSIGNING_WORKER_TOOLS { get; set; }
        public virtual WAMS_POSITION WAMS_POSITION { get; set; }
        public virtual ICollection<WAMS_PROJECT> WAMS_PROJECT { get; set; }
        public virtual ICollection<WAMS_RETURNING_WORKER_TOOLS> WAMS_RETURNING_WORKER_TOOLS { get; set; }
    }
}
