//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_STOCK_APPROVAL
    {
        public string vStockID { get; set; }
        public Nullable<System.DateTime> dDate { get; set; }
        public Nullable<bool> bStatus { get; set; }
    }
}
