//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_AUDIT_TRAILS
    {
        public long bAuditID { get; set; }
        public string vUserName { get; set; }
        public string vActionID { get; set; }
        public string vActionName { get; set; }
        public string vActionType { get; set; }
        public System.DateTime dDate { get; set; }
        public string vDescription { get; set; }
    }
}
