//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ApBusiness.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_PROJECT
    {
        public WAMS_PROJECT()
        {
            this.WAMS_ASSIGNNING_STOCKS = new HashSet<WAMS_ASSIGNNING_STOCKS>();
            this.WAMS_RETURN_LIST = new HashSet<WAMS_RETURN_LIST>();
        }

        [Key]
        public int Id { get; set; }
        public string vProjectID { get; set; }
        public string vProjectName { get; set; }
        public string vLocation { get; set; }
        public string vMainContact { get; set; }
        public string vCompanyName { get; set; }
        public System.DateTime dBeginDate { get; set; }
        public string vStatus { get; set; }
        public string vRemark { get; set; }
        public string vDescription { get; set; }
        public Nullable<bool> iEnable { get; set; }
        public Nullable<int> iClient { get; set; }
        public Nullable<int> iCountry { get; set; }
        public string vSuppervisor { get; set; }
        public Nullable<int> iStore { get; set; }
        public Nullable<System.DateTime> dCreated { get; set; }
        public Nullable<System.DateTime> dModified { get; set; }
        public Nullable<int> iCreated { get; set; }
        public Nullable<int> iModified { get; set; }
        public Nullable<System.DateTime> dEnd { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Project_Client Project_Client { get; set; }
        public virtual ICollection<WAMS_ASSIGNNING_STOCKS> WAMS_ASSIGNNING_STOCKS { get; set; }
        public virtual WAMS_WORKER WAMS_WORKER { get; set; }
        public virtual ICollection<WAMS_RETURN_LIST> WAMS_RETURN_LIST { get; set; }
    }
}
