//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ap.Business.Models
{
    using System;

    public partial class XDynamicReport
    {
        public int Id { get; set; }
        public string Action { get; set; }
        public DateTime PODate { get; set; }
        public string POCode { get; set; }
        public string POType { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string StockCode { get; set; }
        public string StockName { get; set; }
        public string StockType { get; set; }
        public string MRF { get; set; }
        public string Category { get; set; }
        public string Supplier { get; set; }
        public string Unit { get; set; }
        public decimal Quantity { get; set; }
        public decimal QuantityReceived { get; set; }
        public decimal QuantityPending { get; set; }
        public string RalNo { get; set; }
        public string Color { get; set; }
        public string Weight { get; set; }
        public string Note { get; set; }
        public DateTime Created { get; set; }
        public DateTime Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    }
}
