//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ap.Business.Models
{
    using System;

    public partial class XDynamicProjectGroupItemReport
    {
        public int Id { get; set; }
        public int StockId { get; set; }
        public string StockCode { get; set; }
        public string StockName { get; set; }
        public int StockTypeId { get; set; }
        public string StockType { get; set; }
        public int CategoryId { get; set; }
        public string Category { get; set; }
        public int UnitId { get; set; }
        public string Unit { get; set; }
        public decimal QtyStockIn { get; set; }
        public decimal QtyStockReturn { get; set; }
        public decimal QtyStockOut { get; set; }
        public decimal QtyStockRemaining { get; set; }
        public string Weight { get; set; }
        public string Note { get; set; }
        public DateTime Created { get; set; }
        public DateTime Modified { get; set; }
        public int? CreatedById { get; set; }
        public string CreatedBy { get; set; }
        public int? ModifiedById { get; set; }
        public string ModifiedBy { get; set; }
        public string FagFrom { get; set; }
        public int FagId { get; set; }
    }
}
