//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ap.Business.Models
{
    using System;

    public partial class XStockInParent
    {
        public string From { get; set; }
        public string To { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string Srv { get; set; }
        public DateTime Date { get; set; }
    }
}
