//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivablast.Models
{
    using System;

    public partial class V3_DDL_PE
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public int Year { get; set; }
        public int PE_Month { get; set; }
    }
}
