//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivablast.Models
{
    using System;

    public partial class V3_List_StockReturn
    {
        public Nullable<long> No { get; set; }
        public int Id { get; set; }
        public string SRV { get; set; }
        public string Project_Code { get; set; }
        public string Project_Name { get; set; }
        public string Status { get; set; }
        public string Location { get; set; }
        public string Main_Contact { get; set; }
        public string Company { get; set; }
        public string Client { get; set; }
        public string Store { get; set; }
        public string Country { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Remark { get; set; }
    }
}
