//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivablast.Models
{
    using System;

    public partial class V3_List_Stock_Rpt
    {
        public Nullable<long> No { get; set; }
        public int Id { get; set; }
        public string Stock_Code { get; set; }
        public string Stock_Name { get; set; }
        public string Brand { get; set; }
        public string Account_Code { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public string Category { get; set; }
        public Nullable<int> StockID { get; set; }
        public string Stores { get; set; }
        public string Quantity { get; set; }
        public Nullable<double> Weight { get; set; }
        public string RalNo { get; set; }
        public string Color { get; set; }
        public string PartNo { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
    }
}
