//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivablast.Models
{
    using System;
    
    public partial class V3_List_StockIn
    {
        public Nullable<long> No { get; set; }
        public int PE_Id { get; set; }
        public string PE_Code { get; set; }
        public string PE_Type { get; set; }
        public System.DateTime PE_Date { get; set; }
        public decimal? PE_Total { get; set; }
        public string Currency { get; set; }
        public string PE_Location { get; set; }
        public string PE_Status { get; set; }
        public string Supplier { get; set; }
        public string Store { get; set; }
        public string SRV { get; set; }
    }
}
