//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivablast.Models
{
    using System;

    public partial class V3_Price_By_Id
    {
        public Nullable<long> No { get; set; }
        public int Id { get; set; }
        public int Stock_Id { get; set; }
        public string Stock_Code { get; set; }
        public string Stock_Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public string Status { get; set; }
        public int Currency_Id { get; set; }
        public string Currency { get; set; }
        public string Part_No { get; set; }
        public string Ral_No { get; set; }
        public string Color { get; set; }
        public int Supplier_Id { get; set; }
        public string Supplier { get; set; }
        public int Store_Id { get; set; }
        public string Store { get; set; }
        public string Stock_Type { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
