//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ap.Business.Models
{
    using System;

    public partial class XStockIn
    {
        public int Id { get; set; }
        public string StockCode { get; set; }
        public string StockName { get; set; }
        public string Unit { get; set; }
        public decimal Quantity { get; set; }
        public string RalNo { get; set; }
        public string Color { get; set; }
        public string Note { get; set; }
    }
}
