DECLARE @dateClear datetime
SET @dateClear = GETDATE() - 60
-- SELECT @dateClear
DELETE WAMS_FULFILLMENT_DETAIL WHERE vPOID IN (SELECT Id FROM WAMS_PURCHASE_ORDER WHERE dCreated < @dateClear AND vPOStatus='Complete')
DELETE WAMS_PO_DETAILS WHERE vPOID IN (SELECT Id FROM WAMS_PURCHASE_ORDER WHERE dCreated < @dateClear AND vPOStatus='Complete')
DELETE WAMS_PURCHASE_ORDER WHERE dCreated < @dateClear AND vPOStatus='Complete'
DELETE WAMS_REQUISITION_DETAILS WHERE dCreated < @dateClear
DELETE WAMS_REQUISITION_MASTER WHERE dCreated < @dateClear
DELETE WAMS_RETURN_LIST WHERE dCreated < @dateClear
DELETE WAMS_ASSIGNNING_STOCKS WHERE dCreated < @dateClear
DELETE WAMS_STOCK_MANAGEMENT_QUANTITY WHERE dDate < @dateClear
DELETE WAMS_HISTORY_LOG WHERE dDate < @dateClear
DELETE WAMS_STOCK_LOG WHERE dDate < @dateClear
SELECT * FROM WAMS_REPORT
SELECT * FROM WAMS_REPORT_DETAILS
SELECT * FROM [dbo].[WAMS_ERROR_MESSAGE]


