-- WAMS_FUNCTION_MANAGEMENT_WAMS_USER
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WAMS_FUNCTION_MANAGEMENT_WAMS_USER]') AND parent_object_id = OBJECT_ID(N'[dbo].[WAMS_FUNCTION_MANAGEMENT]'))
ALTER TABLE [dbo].[WAMS_FUNCTION_MANAGEMENT] DROP CONSTRAINT [FK_WAMS_FUNCTION_MANAGEMENT_WAMS_USER]
GO

ALTER TABLE [dbo].[WAMS_FUNCTION_MANAGEMENT]  WITH CHECK ADD  CONSTRAINT [FK_WAMS_FUNCTION_MANAGEMENT_WAMS_USER] FOREIGN KEY([bUserID])
REFERENCES [dbo].[WAMS_USER] ([bUserId])
GO

ALTER TABLE [dbo].[WAMS_FUNCTION_MANAGEMENT] CHECK CONSTRAINT [FK_WAMS_FUNCTION_MANAGEMENT_WAMS_USER]
GO

-- WAMS_USER_Store
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WAMS_USER_Store]') AND parent_object_id = OBJECT_ID(N'[dbo].[WAMS_USER]'))
ALTER TABLE [dbo].[WAMS_USER] DROP CONSTRAINT [FK_WAMS_USER_Store]
GO

ALTER TABLE [dbo].[WAMS_USER]  WITH CHECK ADD  CONSTRAINT [FK_WAMS_USER_Store] FOREIGN KEY([storeId])
REFERENCES [dbo].[Store] ([ID])
GO

ALTER TABLE [dbo].[WAMS_USER] CHECK CONSTRAINT [FK_WAMS_USER_Store]
GO

-- WAMS_ASSIGNNING_STOCKS_WAMS_PROJECT && WAMS_ASSIGNNING_STOCKS_WAMS_STOCK
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WAMS_ASSIGNNING_STOCKS_WAMS_PROJECT]') AND parent_object_id = OBJECT_ID(N'[dbo].[WAMS_ASSIGNNING_STOCKS]'))
ALTER TABLE [dbo].[WAMS_ASSIGNNING_STOCKS] DROP CONSTRAINT [FK_WAMS_ASSIGNNING_STOCKS_WAMS_PROJECT]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WAMS_ASSIGNNING_STOCKS_WAMS_STOCK]') AND parent_object_id = OBJECT_ID(N'[dbo].[WAMS_ASSIGNNING_STOCKS]'))
ALTER TABLE [dbo].[WAMS_ASSIGNNING_STOCKS] DROP CONSTRAINT [FK_WAMS_ASSIGNNING_STOCKS_WAMS_STOCK]
GO

ALTER TABLE [dbo].[WAMS_ASSIGNNING_STOCKS]  WITH CHECK ADD  CONSTRAINT [FK_WAMS_ASSIGNNING_STOCKS_WAMS_PROJECT] FOREIGN KEY([vProjectID])
REFERENCES [dbo].[WAMS_PROJECT] ([Id])
GO

ALTER TABLE [dbo].[WAMS_ASSIGNNING_STOCKS] CHECK CONSTRAINT [FK_WAMS_ASSIGNNING_STOCKS_WAMS_PROJECT]
GO

ALTER TABLE [dbo].[WAMS_ASSIGNNING_STOCKS]  WITH CHECK ADD  CONSTRAINT [FK_WAMS_ASSIGNNING_STOCKS_WAMS_STOCK] FOREIGN KEY([vStockID])
REFERENCES [dbo].[WAMS_STOCK] ([Id])
GO

ALTER TABLE [dbo].[WAMS_ASSIGNNING_STOCKS] CHECK CONSTRAINT [FK_WAMS_ASSIGNNING_STOCKS_WAMS_STOCK]
GO


-- WAMS_RETURN_LIST_WAMS_PROJECT && WAMS_RETURN_LIST_WAMS_STOCK
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WAMS_RETURN_LIST_WAMS_PROJECT]') AND parent_object_id = OBJECT_ID(N'[dbo].[WAMS_RETURN_LIST]'))
ALTER TABLE [dbo].[WAMS_RETURN_LIST] DROP CONSTRAINT [FK_WAMS_RETURN_LIST_WAMS_PROJECT]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WAMS_RETURN_LIST_WAMS_STOCK]') AND parent_object_id = OBJECT_ID(N'[dbo].[WAMS_RETURN_LIST]'))
ALTER TABLE [dbo].[WAMS_RETURN_LIST] DROP CONSTRAINT [FK_WAMS_RETURN_LIST_WAMS_STOCK]
GO

ALTER TABLE [dbo].[WAMS_RETURN_LIST]  WITH CHECK ADD  CONSTRAINT [FK_WAMS_RETURN_LIST_WAMS_PROJECT] FOREIGN KEY([vProjectID])
REFERENCES [dbo].[WAMS_PROJECT] ([Id])
GO

ALTER TABLE [dbo].[WAMS_RETURN_LIST] CHECK CONSTRAINT [FK_WAMS_RETURN_LIST_WAMS_PROJECT]
GO

ALTER TABLE [dbo].[WAMS_RETURN_LIST]  WITH CHECK ADD  CONSTRAINT [FK_WAMS_RETURN_LIST_WAMS_STOCK] FOREIGN KEY([vStockID])
REFERENCES [dbo].[WAMS_STOCK] ([Id])
GO

ALTER TABLE [dbo].[WAMS_RETURN_LIST] CHECK CONSTRAINT [FK_WAMS_RETURN_LIST_WAMS_STOCK]
GO

-- WAMS_FULFILLMENT_DETAIL_WAMS_PURCHASE_ORDER && WAMS_FULFILLMENT_DETAIL_WAMS_STOCK
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WAMS_FULFILLMENT_DETAIL_WAMS_PURCHASE_ORDER]') AND parent_object_id = OBJECT_ID(N'[dbo].[WAMS_FULFILLMENT_DETAIL]'))
ALTER TABLE [dbo].[WAMS_FULFILLMENT_DETAIL] DROP CONSTRAINT [FK_WAMS_FULFILLMENT_DETAIL_WAMS_PURCHASE_ORDER]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WAMS_FULFILLMENT_DETAIL_WAMS_STOCK]') AND parent_object_id = OBJECT_ID(N'[dbo].[WAMS_FULFILLMENT_DETAIL]'))
ALTER TABLE [dbo].[WAMS_FULFILLMENT_DETAIL] DROP CONSTRAINT [FK_WAMS_FULFILLMENT_DETAIL_WAMS_STOCK]
GO

ALTER TABLE [dbo].[WAMS_FULFILLMENT_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_WAMS_FULFILLMENT_DETAIL_WAMS_STOCK] FOREIGN KEY([vStockID])
REFERENCES [dbo].[WAMS_STOCK] ([Id])
GO

ALTER TABLE [dbo].[WAMS_FULFILLMENT_DETAIL] CHECK CONSTRAINT [FK_WAMS_FULFILLMENT_DETAIL_WAMS_STOCK]
GO

