-- NOT TRANSACTION
SELECT stock.vStockID, stock.vStockName, stock.bQuantity
FROM WAMS_STOCK AS stock
WHERE stock.bQuantity = 0 
AND NOT EXISTS 
(SELECT 1 FROM WAMS_REQUISITION_DETAILS WHERE vStockID = stock.vStockID)
AND NOT EXISTS
(SELECT 1 FROM WAMS_PO_DETAILS WHERE vProductID = stock.vStockID)
AND NOT EXISTS
(SELECT 1 FROM WAMS_FULFILLMENT_DETAIL WHERE vStockID = stock.vStockID)
AND NOT EXISTS
(SELECT 1 FROM WAMS_ASSIGNNING_STOCKS WHERE vStockID = stock.vStockID)
AND NOT EXISTS
(SELECT 1 FROM WAMS_RETURN_LIST WHERE vStockID = stock.vStockID)
GO
-- HAVE TRANSACTION , BUT OLDEST
DECLARE @date NVARCHAR(22)
SET @date = '2015-01-01'
SELECT DISTINCT stock2.vStockID, stock2.vStockName, stock2.bQuantity, quantity.dDate, quantity.vStatus, quantity.dQuantityChange FROM WAMS_STOCK_MANAGEMENT_QUANTITY quantity 
INNER JOIN 
(SELECT stock.vStockID, stock.vStockName, stock.bQuantity
FROM WAMS_STOCK AS stock
WHERE NOT EXISTS 
(SELECT 1 FROM WAMS_REQUISITION_DETAILS WHERE vStockID = stock.vStockID AND dDateAssign >= @date)
AND NOT EXISTS
(SELECT 1 FROM WAMS_PO_DETAILS WHERE vProductID = stock.vStockID AND dDateAssign >= @date)
AND NOT EXISTS
(SELECT 1 FROM WAMS_FULFILLMENT_DETAIL WHERE vStockID = stock.vStockID AND dDateAssign >= @date)
AND NOT EXISTS
(SELECT 1 FROM WAMS_ASSIGNNING_STOCKS WHERE vStockID = stock.vStockID AND dDateAssign >= @date)
AND NOT EXISTS
(SELECT 1 FROM WAMS_RETURN_LIST WHERE vStockID = stock.vStockID AND dDateReturn >= @date)
) stock2 ON quantity.vStockID = stock2.vStockID
WHERE quantity.dDate = 
(SELECT MAX(dDate) FROM WAMS_STOCK_MANAGEMENT_QUANTITY b WHERE quantity.vStockID = b.vStockID)
ORDER BY stock2.vStockID ASC

-- TEST EXISTS
GO
DECLARE @stock NVARCHAR(100)
SET @stock = 'EQIT0111'
SELECT * FROM WAMS_STOCK WHERE vStockID= @stock
SELECT * FROM WAMS_REQUISITION_DETAILS WHERE vStockID= @stock
SELECT * FROM WAMS_PO_DETAILS WHERE vProductID= @stock
SELECT * FROM WAMS_FULFILLMENT_DETAIL WHERE vStockID= @stock
SELECT * FROM WAMS_ASSIGNNING_STOCKS WHERE vStockID= @stock
SELECT * FROM WAMS_RETURN_LIST WHERE vStockID= @stock

GO
-- TEST HAVE TRANSACTION BUT OLDER
DECLARE @stock NVARCHAR(100)
DECLARE @date NVARCHAR(22)
SET @stock = 'EQIT0111'
SET @date = '2015-01-01'
SELECT * FROM WAMS_REQUISITION_DETAILS WHERE vStockID= @stock AND dDateAssign >= @date ORDER BY dDateAssign ASC
SELECT * FROM WAMS_PO_DETAILS WHERE vProductID= @stock AND dDateAssign >= @date ORDER BY dDateAssign ASC
SELECT * FROM WAMS_FULFILLMENT_DETAIL WHERE vStockID= @stock AND dDateAssign >= @date ORDER BY dDateAssign ASC
SELECT * FROM WAMS_ASSIGNNING_STOCKS WHERE vStockID= @stock AND dDateAssign >= @date ORDER BY dDateAssign ASC
SELECT * FROM WAMS_RETURN_LIST WHERE vStockID= @stock AND dDateReturn >= @date ORDER BY dDateReturn ASC