//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Ap.Data.Entities;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document: BaseEntity
    {
        [Key]
        public int Id { get; set; }
        public string DocumentURL { get; set; }
        public string DocumentDescription { get; set; }
        public int KeyId { get; set; }
        public System.DateTime ActionDate { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public string DocumentName { get; set; }
        public string DocumentTitle { get; set; }
        public string FolderLocation { get; set; }
        public byte[] DocumentFile { get; set; }
        public Nullable<int> ById { get; set; }
    }
}
