//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Ap.Data.Entities;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store : BaseEntity
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Phone { get; set; }
        public string Description { get; set; }
        public string PDFHeader { get; set; }
        public string CoRegNo { get; set; }
        public string GSTRegNo { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string PDFFooter { get; set; }

        public bool? iEnable { get; set; }
        public DateTime? dCreated { get; set; }
        public DateTime? dModified { get; set; }
        public int? iCreated { get; set; }
        public int? iModified { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
