//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_STOCK_MANAGEMENT_QUANTITY
    {
        [Key]
        public int ID { get; set; }
        public int vStockID { get; set; }
        public decimal dQuantityCurrent { get; set; }
        public decimal dQuantityChange { get; set; }
        public decimal dQuantityAfterChange { get; set; }
        public string vStatus { get; set; }
        public string vStatusID { get; set; }
        public Nullable<int> bUserID { get; set; }
        public Nullable<int> vProjectID { get; set; }
        public Nullable<int> vMRF { get; set; }
        public Nullable<int> vPOID { get; set; }
        public Nullable<int> bSupplierID { get; set; }
        public System.DateTime dDate { get; set; }
        public Nullable<int> FromStore { get; set; }
        public Nullable<int> ToStore { get; set; }
    }
}
