//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Ap.Data.Entities;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_STOCK: BaseEntity
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Stock Code")]
        public string vStockID { get; set; }

        [Required]
        [Display(Name = "Stock Name")]
        public string vStockName { get; set; }

        [Display(Name = "Remark")]
        public string vRemark { get; set; }

        [Display(Name = "Unit")]
        public int? bUnitID { get; set; }

        [Display(Name = "Measurement")]
        public long? bMeasurementID { get; set; }

        [Display(Name = "Brand")]
        public string vBrand { get; set; }

        public bool iEnable { get; set; }

        [Display(Name = "Category")]
        public int? bCategoryID { get; set; }

        [Display(Name = "Position")]
        public int? bPositionID { get; set; }

        [Display(Name = "Label")]
        public int? bLabelID { get; set; }

        [Display(Name = "Weight")]
        public decimal? bWeight { get; set; }

        [Display(Name = "Account Code")]
        public string vAccountCode { get; set; }

        [Required]
        [Display(Name = "Store")]
        public int StoreId { get; set; }

        [Display(Name = "Type")]
        public int? iType { get; set; }

        [Display(Name = "Part No")]
        public string PartNo { get; set; }

        [Display(Name = "Part No For")]
        public string PartNoFor { get; set; }

        [Display(Name = "Part No Min (Qty)")]
        public int? PartNoMiniQty { get; set; }

        [Display(Name = "Ral No")]
        public string RalNo { get; set; }

        [Display(Name = "Color")]
        public string ColorName { get; set; }

        [Display(Name = "Category Sub")]
        public int? SubCategory { get; set; }

        [Display(Name = "User For Paint")]
        public int? UserForPaint { get; set; }

        public DateTime? dCreated { get; set; }
        
        public DateTime? dModified { get; set; }
        
        public int? iCreated { get; set; }

        public int? iModified { get; set; }

        public byte[] Timestamp { get; set; }

        public string Position { get; set; }

        public string Unit { get; set; }

        public string Category { get; set; }

        public string Label { get; set; }

        public string Type { get; set; }

        public string Files { get; set; }

        [Display(Name = "Orginal Name")]
        public string OrginalFile { get; set; }

        [Display(Name = "File Path")]
        public string FilePath { get; set; }
    }
}
