//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_POSITION
    {
        public WAMS_POSITION()
        {
            this.WAMS_CAR = new HashSet<WAMS_CAR>();
            this.WAMS_EQUIPMENT = new HashSet<WAMS_EQUIPMENT>();
            this.WAMS_WORKER = new HashSet<WAMS_WORKER>();
        }

        [Key]
        public long bPositionID { get; set; }
        public string vPositionName { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual ICollection<WAMS_CAR> WAMS_CAR { get; set; }
        public virtual ICollection<WAMS_EQUIPMENT> WAMS_EQUIPMENT { get; set; }
        public virtual ICollection<WAMS_WORKER> WAMS_WORKER { get; set; }
    }
}
