//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Ap.Data.Entities;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_REQUISITION_DETAILS : BaseEntity
    {
        [Key]
        public int ID { get; set; }
        public Nullable<int> vMRF { get; set; }
        public Nullable<int> vStockID { get; set; }
        public Nullable<decimal> fQuantity { get; set; }
        public Nullable<double> fUMO { get; set; }
        public Nullable<double> fInStock { get; set; }
        public Nullable<decimal> fTobePurchased { get; set; }
        public Nullable<int> iFollowUpRequired { get; set; }
        public Nullable<int> iPurchased { get; set; }
        public Nullable<int> iSent { get; set; }
        public string vStatus { get; set; }
        public Nullable<bool> iEnable { get; set; }
        public Nullable<System.DateTime> dDateAssign { get; set; }
        public Nullable<int> iStore { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> dCreated { get; set; }
        public Nullable<System.DateTime> dModified { get; set; }
        public Nullable<int> iCreated { get; set; }
        public Nullable<int> iModified { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
