//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_USEFOR
    {
        public WAMS_USEFOR()
        {
            this.WAMS_PAINT = new HashSet<WAMS_PAINT>();
        }

        [Key]
        public long bUseForID { get; set; }
        public string vUseForName { get; set; }
    
        public virtual ICollection<WAMS_PAINT> WAMS_PAINT { get; set; }
    }
}
