//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Ap.Data.Entities;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_SUPPLIER : BaseEntity
    {
        public WAMS_SUPPLIER()
        {
            this.WAMS_PURCHASE_ORDER = new HashSet<WAMS_PURCHASE_ORDER>();
            this.WAMS_RETURN_PRODUCT_TO_SUPPLIER = new HashSet<WAMS_RETURN_PRODUCT_TO_SUPPLIER>();
        }

        [Key]
        public int bSupplierID { get; set; }
        public string vSupplierName { get; set; }
        public string vAddress { get; set; }
        public string vCity { get; set; }
        public string vPhone1 { get; set; }
        public string vPhone2 { get; set; }
        public string vMobile { get; set; }
        public string vFax { get; set; }
        public string vEmail { get; set; }
        public string vContactPerson { get; set; }
        public Nullable<decimal> fTotalMoney { get; set; }
        public Nullable<int> bSupplierTypeID { get; set; }
        public Nullable<bool> iEnable { get; set; }
        public Nullable<int> iService { get; set; }
        public Nullable<System.DateTime> dDateCreate { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<bool> iMarket { get; set; }
        public Nullable<int> iStore { get; set; }
        public Nullable<int> iPayment { get; set; }
        public Nullable<System.DateTime> dCreated { get; set; }
        public Nullable<System.DateTime> dModified { get; set; }
        public Nullable<int> iCreated { get; set; }
        public Nullable<int> iModified { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual ICollection<WAMS_PURCHASE_ORDER> WAMS_PURCHASE_ORDER { get; set; }
        public virtual ICollection<WAMS_RETURN_PRODUCT_TO_SUPPLIER> WAMS_RETURN_PRODUCT_TO_SUPPLIER { get; set; }
        public virtual WAMS_SUPPLIER_TYPE WAMS_SUPPLIER_TYPE { get; set; }
    }
}
