//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_SHIPMENT
    {
        [Key]
        public string iShipID { get; set; }
        public Nullable<System.DateTime> dShipDate { get; set; }
        public string vCountry { get; set; }
        public string vRemark { get; set; }
        public Nullable<System.DateTime> dETAatPort { get; set; }
        public Nullable<System.DateTime> dETABC { get; set; }
        public string vForWhat { get; set; }
        public string vPaymentStatus { get; set; }
        public Nullable<double> fTotalShip { get; set; }
        public Nullable<int> iEnable { get; set; }
    }
}
