//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Ap.Data.Entities;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_ASSIGNNING_STOCKS: BaseEntity
    {
        [Key]
        public int bAssignningStockID { get; set; }
        public int vStockID { get; set; }
        public int? vProjectID { get; set; }
        public decimal? bQuantity { get; set; }
        public string vWorkerID { get; set; }
        public string SIV { get; set; }
        public string vMRF { get; set; }
        public int? FromStore { get; set; }
        public int? ToStore { get; set; }
        public DateTime? dCreated { get; set; }
        public DateTime? dModified { get; set; }
        public int? iCreated { get; set; }
        public int? iModified { get; set; }
        public int? AccCheck { get; set; }
        public string AccDescription { get; set; }
        public DateTime? AccdCreated { get; set; }
        public DateTime? AccdModified { get; set; }
        public int? AcciCreated { get; set; }
        public int? AcciModidied { get; set; }
        public bool? FlagFile { get; set; }
        public string Description { get; set; }
        public byte[] Timestamp { get; set; }
    
        //public virtual WAMS_PROJECT WAMS_PROJECT { get; set; }
        //public virtual WAMS_STOCK WAMS_STOCK { get; set; }

        public DateTime? DateStockOut { get; set; }
    }
}
