//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_CATALOGUE_CONFIGURATION
    {
        [Key]
        public long bConfiguration { get; set; }
        public string vConfigurationName { get; set; }
        public string vDisplay1 { get; set; }
        public string vDisplay2 { get; set; }
        public string vDisplay3 { get; set; }
        public string vDisplay4 { get; set; }
        public string vDisplay5 { get; set; }
        public string vDisplay6 { get; set; }
        public string vColor { get; set; }
        public string vStockType { get; set; }
    }
}
