//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_SERVICE_HISTORY
    {
        [Key]
        public long bServiceID { get; set; }
        public System.DateTime dServiceDate { get; set; }
        public Nullable<System.DateTime> dReturnDate { get; set; }
        public string vCondition { get; set; }
    }
}
