//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivablast.Models
{
    using System;

    public partial class V3_Information_Stock
    {
        public int Id { get; set; }
        public string Stock_Code { get; set; }
        public string Stock_Name { get; set; }
        public string Unit { get; set; }
        public string Type { get; set; }
        public string Category { get; set; }
        public string Ral_No { get; set; }
        public string Color { get; set; }
        public string Part_No { get; set; }
        public int TypeId { get; set; }
        public int CategoryId { get; set; }
        public int UnitId { get; set; }
        public Nullable<int> StockID { get; set; }
        public string Stores { get; set; }
        public string Quantity { get; set; }
    }
}
