//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivablast.Models
{
    using System;

    public partial class V3_List_StockIn_Detail
    {
        public int Id { get; set; }
        public int PE_Id { get; set; }
        public string PE_Code { get; set; }
        public int Stock_Id { get; set; }
        public string Stock_Code { get; set; }
        public string Stock_Name { get; set; }
        public decimal Qty_Total { get; set; }
        public decimal Qty_Received { get; set; }
        public decimal Qty_Pending { get; set; }
        public decimal ImportTax { get; set; }
        public string InvoiceNo { get; set; }
        public DateTime InvoiceDate { get; set; }
        public string Description { get; set; }
        public string MRF { get; set; }
        public string SRV { get; set; }
        public string Unit { get; set; }
        public string Type { get; set; }
        public string Category { get; set; }
        public string RalNo { get; set; }
        public string Color { get; set; }
        public string PartNo { get; set; }
    }
}
