//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivablast.Models
{
    using System;
    
    public partial class V3_PE_PDF
    {
        public int Id { get; set; }
        public string PE { get; set; }
        public System.DateTime PE_Date { get; set; }
        public decimal Total { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string Location { get; set; }
        public DateTime Deliver_Date { get; set; }
        public string From { get; set; }
        public string Address { get; set; }
        public string TaxCode { get; set; }
        public string CC { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string PeStaff { get; set; }
        public string CoRegNo { get; set; }
        public string GSTRegNo { get; set; }
        public string PengerangSite { get; set; }
        public string GSTAddress { get; set; }
        
        public string Type { get; set; }
        public string Project_Code { get; set; }
        public string Project_Name { get; set; }

        #region Supplier
        public string Supplier { get; set; }
        public string SupplierAtt { get; set; }
        public string SupplierEmail { get; set; }
        public string SupplierTel { get; set; }
        public string SupplierFax { get; set; }

        #endregion
        
        public string Currency { get; set; }
        public string Store { get; set; }
        public string Payment_Term { get; set; }
        public string PriceEval { get; set; }
        public string QuanlityEval { get; set; }
        public string DeliveryEval { get; set; }
        public string Comformancy { get; set; }

        public decimal TotalVAT { get; set; }
        public decimal TotalNotVAT { get; set; }
        
    }
}
