//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivablast.Models
{
    using System;

    public partial class V3_Pe_Detail
    {
        public int Id { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> VAT { get; set; }
        public Nullable<decimal> Item_Total { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string PE { get; set; }
        public int Stock_Id { get; set; }
        public string Stock_Code { get; set; }
        public string Stock_Name { get; set; }
        public string Unit { get; set; }
        public string Type { get; set; }
        public string MRF { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<int> Created_Id { get; set; }
        public Nullable<int> Price_Id { get; set; }
        public decimal? UnitPrice { get; set; }
        public int? ImportTaxt { get; set; }
    }
}
