//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivablast.Models
{
    using System;

    public partial class V3_Pe_Detail_Data
    {
        public int Id { get; set; }
        public decimal Quantity { get; set; }
        public int Price_Id { get; set; }
        public decimal UnitPrice { get; set; }
        public int Discount { get; set; }
        public int VAT { get; set; }
        public decimal ItemTotal { get; set; }
        public DateTime DeliveryDate { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public int StockId { get; set; }
        public string MRFId { get; set; }
    }
}
