//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivablast.Models
{
    using System;
    
    public partial class V3_Requisition_Master
    {
        public int Id { get; set; }
        public string vMRF { get; set; }
        public string vFrom { get; set; }
        public Nullable<int> vProjectID { get; set; }
        public string Project_Code { get; set; }
        public string Project_Name { get; set; }
        public Nullable<System.DateTime> dDeliverDate { get; set; }
        public string vDeliverLocation { get; set; }
        public string vRemark { get; set; }
        public Nullable<bool> iEnable { get; set; }
        public string vStatus { get; set; }
        public Nullable<int> iStore { get; set; }
        public Nullable<System.DateTime> dCreated { get; set; }
        public Nullable<System.DateTime> dModified { get; set; }
        public Nullable<int> iCreated { get; set; }
        public Nullable<int> iModified { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
