//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Ap.Data.Entities;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Price: BaseEntity
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<System.DateTime> dStart { get; set; }
        public Nullable<System.DateTime> dEnd { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> iEnable { get; set; }
        public Nullable<System.DateTime> dCreated { get; set; }
        public Nullable<System.DateTime> dModified { get; set; }
        public Nullable<int> iCreated { get; set; }
        public Nullable<int> iModified { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
