//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Ap.Data.Entities;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Client : BaseEntity
    {
        public Project_Client()
        {
            //this.WAMS_PROJECT = new HashSet<WAMS_PROJECT>();
        }

        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> dCreated { get; set; }
        public Nullable<int> iCreated { get; set; }
    
        //public virtual ICollection<WAMS_PROJECT> WAMS_PROJECT { get; set; }
    }
}
