//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV
    {
        [Key]
        public int Id { get; set; }
        public string SRV1 { get; set; }
        public string Status { get; set; }
        public System.DateTime dDate { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
