//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_RETURN_PRODUCT_TO_SUPPLIER
    {
        [Key]
        public long bReturnID { get; set; }
        public string vStockID { get; set; }
        public Nullable<int> bSupplierID { get; set; }
        public Nullable<double> fQuantity { get; set; }
        public Nullable<System.DateTime> dDateReturn { get; set; }
        public string vCondition { get; set; }
        public Nullable<int> iServiceFlag { get; set; }
        public string vRemark { get; set; }
        public string vPOID { get; set; }
        public Nullable<int> iEnable { get; set; }
        public Nullable<double> fStockQuantity { get; set; }
        public string chkPurchased { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual WAMS_SUPPLIER WAMS_SUPPLIER { get; set; }
    }
}
