//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_PROJECT_SUPERVISOR
    {
        [Key]
        public long bProjectSupervisorID { get; set; }
        public string bSupervisorID { get; set; }
        public string vProjectID { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
