//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_REPORT_DETAILS
    {
        [Key]
        public long bReportDetailID { get; set; }
        public Nullable<long> bReportID { get; set; }
        public string vStockName { get; set; }
        public Nullable<double> bQuantity { get; set; }
        public Nullable<System.DateTime> dDateAssign { get; set; }
        public string vWorkerID { get; set; }
        public string vWorkerName { get; set; }
        public string vStockID { get; set; }
        public string vDescription { get; set; }
    }
}
