//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_SUPPLIER_TYPE
    {
        public WAMS_SUPPLIER_TYPE()
        {
            this.WAMS_SUPPLIER = new HashSet<WAMS_SUPPLIER>();
        }

        [Key]
        public int bSupplierTypeID { get; set; }
        public string vSupplierTypeName { get; set; }
    
        public virtual ICollection<WAMS_SUPPLIER> WAMS_SUPPLIER { get; set; }
    }
}
