//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_MEASUREMENT
    {
        public WAMS_MEASUREMENT()
        {
            this.WAMS_STOCK = new HashSet<WAMS_STOCK>();
        }

        [Key]
        public long bMeasurementID { get; set; }
        public string vMeasurementName { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual ICollection<WAMS_STOCK> WAMS_STOCK { get; set; }
    }
}
