//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Ap.Data.Entities;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_CURRENCY_TYPE: BaseEntity
    {
        public WAMS_CURRENCY_TYPE()
        {
            this.WAMS_PURCHASE_ORDER = new HashSet<WAMS_PURCHASE_ORDER>();
        }

        [Key]
        public int bCurrencyTypeID { get; set; }
        public string vCurrencyName { get; set; }
    
        public virtual ICollection<WAMS_PURCHASE_ORDER> WAMS_PURCHASE_ORDER { get; set; }
    }
}
