//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_STOCK_MANAGEMENT_QUANTITY
    {
        [Key]
        public int ID { get; set; }
        public int vStockID { get; set; }
        public decimal dQuantityCurrent { get; set; }
        public decimal dQuantityChange { get; set; }
        public decimal dQuantityAfterChange { get; set; }
        public string vStatus { get; set; }
        public string vStatusID { get; set; }
        public int? bUserID { get; set; }
        public int? vProjectID { get; set; }
        public int? vMRF { get; set; }
        public string MRFCode { get; set; }
        public int? vPOID { get; set; }
        public int? bSupplierID { get; set; }
        public System.DateTime dDate { get; set; }
        public int? FromStore { get; set; }
        public int? ToStore { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string StockCode { get; set; }
        public string StockName { get; set; }
        public int StockTypeId { get; set; }
        public string StockType { get; set; }
        public int CategoryId { get; set; }
        public string Category { get; set; }
        public int UnitId { get; set; }
        public string Unit { get; set; }
        public string Supplier { get; set; }
        public DateTime? PODate { get; set; }
        public string POCode { get; set; }
        public string Weight { get; set; }
        public string Note { get; set; }
        public DateTime Created { get; set; }
        public DateTime Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string FagFrom { get; set; }
        public int FagId { get; set; }
    }
}
