//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Ap.Data.Entities;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;

    public partial class WAMS_PROJECT : BaseEntity
    {
        public WAMS_PROJECT()
        {
            //this.WAMS_ASSIGNNING_STOCKS = new HashSet<WAMS_ASSIGNNING_STOCKS>();
            //this.WAMS_RETURN_LIST = new HashSet<WAMS_RETURN_LIST>();
        }
    
        [Key]
        public int Id { get; set; }
        [DisplayName("Project Code")] 
        public string vProjectID { get; set; }
        [DisplayName("Project Name")] 
        public string vProjectName { get; set; }
        [DisplayName("Project Location")] 
        public string vLocation { get; set; }
        [DisplayName("Contact")] 
        public string vMainContact { get; set; }
        [DisplayName("Company")] 
        public string vCompanyName { get; set; }
        [DisplayName("Begin Date")] 
        public System.DateTime dBeginDate { get; set; }
        public string vRemark { get; set; }
        public string vDescription { get; set; }
        public Nullable<bool> iEnable { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Suppervisor { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<System.DateTime> dCreated { get; set; }
        public Nullable<System.DateTime> dModified { get; set; }
        public Nullable<int> iCreated { get; set; }
        public Nullable<int> iModified { get; set; }
        [DisplayName("End Date")] 
        public Nullable<System.DateTime> dEnd { get; set; }
        public byte[] Timestamp { get; set; }
        public int? StatusId { get; set; }
    }
}
