//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_ASSIGNING_WORKER_TOOLS
    {
        [Key]
        public long bWorkerToolID { get; set; }
        public string vWorkerID { get; set; }
        public string vStockID { get; set; }
        public Nullable<long> bQuantity { get; set; }
        public string vStatus { get; set; }
        public Nullable<System.DateTime> dAssigningDate { get; set; }
        public string vReturned { get; set; }
        public string vReason { get; set; }
    
        public virtual WAMS_WORKER WAMS_WORKER { get; set; }
    }
}
