//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Ap.Business.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAMS_SHIPMENT_DETAIL
    {
        [Key]
        public int ID { get; set; }
        public string iShipID { get; set; }
        public string vPOID { get; set; }
        public Nullable<System.DateTime> dPODate { get; set; }
        public string vPOStatus { get; set; }
        public string vCusStatement { get; set; }
        public Nullable<System.DateTime> dStatementDate { get; set; }
        public Nullable<double> fImportTax { get; set; }
        public Nullable<double> fVAT { get; set; }
        public Nullable<double> fRealArriveQuantity { get; set; }
        public string vCurrencyName { get; set; }
        public string vClearanceByShipper { get; set; }
        public string vGoodDescription { get; set; }
        public Nullable<int> iEnable { get; set; }
    }
}
