DECLARE @po NVARCHAR(30)
SET @po='DEC/14/7887'
SELECT * FROM dbo.WAMS_PO_DETAILS WHERE vPOID=@po
SELECT * FROM dbo.WAMS_PURCHASE_ORDER WHERE vPOID=@po
SELECT * FROM dbo.WAMS_FULFILLMENT_DETAIL WHERE vPOID=@po
SELECT * FROM dbo.WAMS_STOCK 
WHERE vStockID IN (SELECT vProductId FROM WAMS_PO_DETAILS WHERE vPOID=@po AND iEnable=0)
SELECT * FROM dbo.WAMS_STOCK_MANAGEMENT_QUANTITY 
WHERE vStockID IN (SELECT vProductId FROM WAMS_PO_DETAILS WHERE vPOID=@po AND iEnable=0)

UPDATE dbo.WAMS_PO_DETAILS SET vPODetailStatus='Open' where vPOID=@po --AND ID=52796
UPDATE dbo.WAMS_PURCHASE_ORDER SET vPOStatus='Open' where vPOID=@po
DELETE dbo.WAMS_FULFILLMENT_DETAIL WHERE vPOID=@po
UPDATE dbo.WAMS_STOCK SET bQuantity = (bQuantity -1) WHERE vStockID='F1000379'
UPDATE dbo.WAMS_STOCK SET bQuantity = (bQuantity -3) WHERE vStockID='F1000380'
DELETE dbo.WAMS_STOCK_MANAGEMENT_QUANTITY WHERE vPOID=@po
UPDATE dbo.WAMS_STOCK_MANAGEMENT_QUANTITY 
SET dQuantityCurrent = (dQuantityCurrent - 1)
,dQuantityAfterChange = (dQuantityAfterChange - 1) WHERE ID > 68502 AND vStockID='F1000379'
UPDATE dbo.WAMS_STOCK_MANAGEMENT_QUANTITY 
SET dQuantityCurrent = (dQuantityCurrent - 3)
,dQuantityAfterChange = (dQuantityAfterChange - 3) WHERE ID > 68502 AND vStockID='F1000380'

